#This file stores configuration options for AngelicaShaders, such as the currently active shaderpack
#Thu Jan 29 16:50:18 NOVT 2026
disableUpdateMessage=false
enableShaders=false
maxShadowRenderDistance=12
shaderPack=ComplementaryUnbound_r5.5.1.zip
