#This file stores configuration options for AngelicaShaders, such as the currently active shaderpack
#Mon Jul 21 13:48:50 NOVT 2025
disableUpdateMessage=false
enableShaders=false
maxShadowRenderDistance=12
shaderPack=ComplementaryUnbound_r5.5.1.zip
