#This file stores configuration options for AngelicaShaders, such as the currently active shaderpack
#Sun Feb 01 14:32:02 NOVT 2026
disableUpdateMessage=false
enableShaders=false
maxShadowRenderDistance=12
shaderPack=ComplementaryUnbound_r5.5.1.zip
